export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.notizihub.com';

export const LINGUE = [
  { id: 'it', nome: 'Italiano', flag: '🇮🇹', locale: 'it-IT' },
  { id: 'en', nome: 'English',  flag: '🇺🇸', locale: 'en-US' },
  { id: 'es', nome: 'Español',  flag: '🇪🇸', locale: 'es-ES' },
  { id: 'de', nome: 'Deutsch',  flag: '🇩🇪', locale: 'de-DE' },
  { id: 'fr', nome: 'Français', flag: '🇫🇷', locale: 'fr-FR' },
  { id: 'pt', nome: 'Português',flag: '🇧🇷', locale: 'pt-BR' },
];

export const NICCHIE_META = [
  { id: 'finanza', colore: '#1a56db', bg: '#EBF5FF' },
  { id: 'crypto', colore: '#b45309', bg: '#FFFBEB' },
  { id: 'tech', colore: '#6d28d9', bg: '#F5F3FF' },
  { id: 'salute', colore: '#065f46', bg: '#ECFDF5' },
  { id: 'viaggi', colore: '#9d174d', bg: '#FFF1F2' },
  { id: 'motori', colore: '#166534', bg: '#F0FDF4' },
  { id: 'gaming', colore: '#86198f', bg: '#FDF4FF' },
  { id: 'casa', colore: '#44403c', bg: '#FAFAF9' },
  { id: 'lavoro', colore: '#991b1b', bg: '#FEF2F2' },
  { id: 'sport', colore: '#0f766e', bg: '#F0FDFA' },
  { id: 'assicurazioni', colore: '#1a56db', bg: '#EBF5FF' },
  { id: 'fisco', colore: '#991b1b', bg: '#FEF2F2' },
  { id: 'pensioni', colore: '#44403c', bg: '#FAFAF9' },
  { id: 'prestiti', colore: '#b45309', bg: '#FFFBEB' },
  { id: 'trading', colore: '#065f46', bg: '#ECFDF5' },
  { id: 'cucina', colore: '#9d174d', bg: '#FFF1F2' },
  { id: 'moda', colore: '#86198f', bg: '#FDF4FF' },
  { id: 'bellezza', colore: '#9d174d', bg: '#FFF1F2' },
  { id: 'animali', colore: '#166534', bg: '#F0FDF4' },
  { id: 'ambiente', colore: '#166534', bg: '#F0FDF4' },
  { id: 'startup', colore: '#6d28d9', bg: '#F5F3FF' },
  { id: 'smartphone', colore: '#6d28d9', bg: '#F5F3FF' },
  { id: 'scienza', colore: '#0f766e', bg: '#F0FDFA' },
  { id: 'psicologia', colore: '#6d28d9', bg: '#F5F3FF' },
  { id: 'cinema', colore: '#44403c', bg: '#FAFAF9' },
  { id: 'energia', colore: '#b45309', bg: '#FFFBEB' },
];

export const NICCHIE_DESC = {
  finanza: {
    it: 'Tutto ciò che devi sapere per gestire al meglio i tuoi soldi: risparmio, investimenti, banche, mutui e molto altro. Aggiornamenti quotidiani per migliorare la tua salute finanziaria.',
    en: 'Everything you need to know to manage your money better: savings, investments, banks, mortgages and much more. Daily updates to improve your financial health.',
    es: 'Todo lo que necesitas saber para gestionar mejor tu dinero: ahorro, inversiones, bancos, hipotecas y mucho más. Actualizaciones diarias para mejorar tu salud financiera.',
    de: 'Alles, was Sie wissen müssen, um Ihr Geld besser zu verwalten: Sparen, Investitionen, Banken, Hypotheken und vieles mehr. Tägliche Updates zur Verbesserung Ihrer finanziellen Gesundheit.',
    fr: "Tout ce que vous devez savoir pour mieux gérer votre argent : épargne, investissements, banques, prêts immobiliers et bien plus encore. Mises à jour quotidiennes pour améliorer votre santé financière.",
    pt: 'Tudo o que você precisa saber para gerenciar melhor seu dinheiro: poupança, investimentos, bancos, hipotecas e muito mais. Atualizações diárias para melhorar sua saúde financeira.',
  },
  crypto: {
    it: 'Le ultime notizie su Bitcoin, Ethereum, altcoin, DeFi e NFT. Analisi di mercato, guide per principianti e aggiornamenti sul mondo Web3 in tempo reale.',
    en: 'The latest news on Bitcoin, Ethereum, altcoins, DeFi and NFTs. Market analysis, beginner guides and real-time Web3 updates.',
    es: 'Las últimas noticias sobre Bitcoin, Ethereum, altcoins, DeFi y NFTs. Análisis de mercado, guías para principiantes y actualizaciones del mundo Web3 en tiempo real.',
    de: 'Die neuesten Nachrichten zu Bitcoin, Ethereum, Altcoins, DeFi und NFTs. Marktanalysen, Anleitungen für Einsteiger und Web3-Updates in Echtzeit.',
    fr: 'Les dernières actualités sur Bitcoin, Ethereum, altcoins, DeFi et NFTs. Analyses de marché, guides pour débutants et mises à jour du monde Web3 en temps réel.',
    pt: 'As últimas notícias sobre Bitcoin, Ethereum, altcoins, DeFi e NFTs. Análises de mercado, guias para iniciantes e atualizações do mundo Web3 em tempo real.',
  },
  tech: {
    it: 'Intelligenza artificiale, gadget, software, cybersecurity e innovazione digitale. Scopri le ultime tendenze tecnologiche e come stanno cambiando il mondo.',
    en: 'Artificial intelligence, gadgets, software, cybersecurity and digital innovation. Discover the latest tech trends and how they are changing the world.',
    es: 'Inteligencia artificial, gadgets, software, ciberseguridad e innovación digital. Descubre las últimas tendencias tecnológicas y cómo están cambiando el mundo.',
    de: 'Künstliche Intelligenz, Gadgets, Software, Cybersicherheit und digitale Innovation. Entdecken Sie die neuesten Technologietrends und wie sie die Welt verändern.',
    fr: "Intelligence artificielle, gadgets, logiciels, cybersécurité et innovation numérique. Découvrez les dernières tendances technologiques et comment elles changent le monde.",
    pt: 'Inteligência artificial, gadgets, software, cibersegurança e inovação digital. Descubra as últimas tendências tecnológicas e como estão mudando o mundo.',
  },
  salute: {
    it: 'Notizie su medicina, alimentazione, fitness e benessere mentale. Consigli pratici e aggiornamenti scientifici per vivere meglio ogni giorno.',
    en: 'News on medicine, nutrition, fitness and mental wellness. Practical tips and scientific updates to live better every day.',
    es: 'Noticias sobre medicina, nutrición, fitness y bienestar mental. Consejos prácticos y actualizaciones científicas para vivir mejor cada día.',
    de: 'Nachrichten über Medizin, Ernährung, Fitness und mentales Wohlbefinden. Praktische Tipps und wissenschaftliche Updates für ein besseres Leben.',
    fr: 'Actualités sur la médecine, la nutrition, le fitness et le bien-être mental. Conseils pratiques et mises à jour scientifiques pour mieux vivre chaque jour.',
    pt: 'Notícias sobre medicina, nutrição, fitness e bem-estar mental. Dicas práticas e atualizações científicas para viver melhor a cada dia.',
  },
  viaggi: {
    it: "Destinazioni, offerte, consigli di viaggio e guide pratiche per esplorare il mondo. Dai viaggi economici al lusso, trova l'ispirazione per la tua prossima avventura.",
    en: 'Destinations, deals, travel tips and practical guides to explore the world. From budget travel to luxury, find inspiration for your next adventure.',
    es: 'Destinos, ofertas, consejos de viaje y guías prácticas para explorar el mundo. Desde viajes económicos hasta el lujo, encuentra inspiración para tu próxima aventura.',
    de: 'Reiseziele, Angebote, Reisetipps und praktische Guides zur Weltentdeckung. Von Budgetreisen bis Luxus — finden Sie Inspiration für Ihr nächstes Abenteuer.',
    fr: "Destinations, offres, conseils de voyage et guides pratiques pour explorer le monde. Du voyage économique au luxe, trouvez l'inspiration pour votre prochaine aventure.",
    pt: 'Destinos, ofertas, dicas de viagem e guias práticos para explorar o mundo. De viagens econômicas ao luxo, encontre inspiração para sua próxima aventura.',
  },
  motori: {
    it: 'Ultime notizie su auto, moto, elettrico e mercato automotive. Test, confronti, novità di settore e consigli per chi ama i motori.',
    en: 'Latest news on cars, motorcycles, electric vehicles and the automotive market. Tests, comparisons, industry news and tips for motor enthusiasts.',
    es: 'Últimas noticias sobre coches, motos, eléctricos y el mercado automovilístico. Pruebas, comparativas, novedades del sector y consejos para los amantes del motor.',
    de: 'Neueste Nachrichten zu Autos, Motorrädern, Elektrofahrzeugen und dem Automobilmarkt. Tests, Vergleiche, Branchennews und Tipps für Motorsport-Enthusiasten.',
    fr: 'Dernières actualités sur les voitures, motos, véhicules électriques et le marché automobile. Tests, comparatifs, nouveautés du secteur et conseils pour les passionnés de moteurs.',
    pt: 'Últimas notícias sobre carros, motos, elétricos e o mercado automotivo. Testes, comparações, novidades do setor e dicas para os amantes de motores.',
  },
  gaming: {
    it: 'Videogiochi, esport, recensioni, trailer e notizie dal mondo del gaming. Rimani aggiornato su PC, console, mobile e tornei internazionali.',
    en: 'Video games, esports, reviews, trailers and news from the gaming world. Stay updated on PC, console, mobile and international tournaments.',
    es: 'Videojuegos, esports, reseñas, tráilers y noticias del mundo del gaming. Mantente actualizado sobre PC, consola, móvil y torneos internacionales.',
    de: 'Videospiele, Esports, Rezensionen, Trailer und Nachrichten aus der Gaming-Welt. Bleiben Sie über PC, Konsole, Mobile und internationale Turniere informiert.',
    fr: 'Jeux vidéo, esports, critiques, bandes-annonces et actualités du monde du gaming. Restez informé sur PC, console, mobile et tournois internationaux.',
    pt: 'Videogames, esports, análises, trailers e notícias do mundo dos games. Fique atualizado sobre PC, console, mobile e torneios internacionais.',
  },
  casa: {
    it: 'Mercato immobiliare, arredamento, ristrutturazioni e consigli per la casa. Prezzi, tendenze e guide per comprare, vendere o affittare casa.',
    en: 'Real estate market, home decor, renovations and house tips. Prices, trends and guides to buy, sell or rent a home.',
    es: 'Mercado inmobiliario, decoración del hogar, reformas y consejos para el hogar. Precios, tendencias y guías para comprar, vender o alquilar una casa.',
    de: 'Immobilienmarkt, Inneneinrichtung, Renovierungen und Haustipps. Preise, Trends und Leitfäden zum Kaufen, Verkaufen oder Mieten von Immobilien.',
    fr: 'Marché immobilier, décoration intérieure, rénovations et conseils pour la maison. Prix, tendances et guides pour acheter, vendre ou louer un logement.',
    pt: 'Mercado imobiliário, decoração de interiores, reformas e dicas para a casa. Preços, tendências e guias para comprar, vender ou alugar um imóvel.',
  },
  lavoro: {
    it: 'Offerte di lavoro, consigli per la carriera, smart working e mercato del lavoro. Tutto ciò che ti serve per crescere professionalmente e trovare il lavoro dei tuoi sogni.',
    en: 'Job offers, career advice, remote work and the job market. Everything you need to grow professionally and find your dream job.',
    es: 'Ofertas de trabajo, consejos profesionales, teletrabajo y mercado laboral. Todo lo que necesitas para crecer profesionalmente y encontrar el trabajo de tus sueños.',
    de: 'Stellenangebote, Karrieretipps, Homeoffice und Arbeitsmarkt. Alles, was Sie brauchen, um professionell zu wachsen und Ihren Traumjob zu finden.',
    fr: "Offres d'emploi, conseils de carrière, télétravail et marché du travail. Tout ce dont vous avez besoin pour progresser professionnellement.",
    pt: 'Ofertas de emprego, dicas de carreira, trabalho remoto e mercado de trabalho. Tudo o que você precisa para crescer profissionalmente e encontrar o emprego dos seus sonhos.',
  },
  sport: {
    it: 'Calcio, basket, tennis, Formula 1 e molto altro. Risultati, classifiche, trasferimenti e analisi tattiche aggiornate ogni giorno.',
    en: 'Football, basketball, tennis, Formula 1 and much more. Results, standings, transfers and tactical analysis updated every day.',
    es: 'Fútbol, baloncesto, tenis, Fórmula 1 y mucho más. Resultados, clasificaciones, fichajes y análisis tácticos actualizados cada día.',
    de: 'Fußball, Basketball, Tennis, Formel 1 und vieles mehr. Ergebnisse, Tabellen, Transfers und taktische Analysen, täglich aktualisiert.',
    fr: 'Football, basketball, tennis, Formule 1 et bien plus encore. Résultats, classements, transferts et analyses tactiques mis à jour chaque jour.',
    pt: 'Futebol, basquete, tênis, Fórmula 1 e muito mais. Resultados, classificações, transferências e análises táticas atualizadas todos os dias.',
  },
  assicurazioni: {
    it: 'Guida alle assicurazioni: RC auto, vita, salute, casa e viaggi. Confronta polizze, scopri come risparmiare e scegli la copertura giusta per te.',
    en: 'Insurance guide: car, life, health, home and travel. Compare policies, discover how to save and choose the right coverage for you.',
    es: 'Guía de seguros: automóvil, vida, salud, hogar y viajes. Compara pólizas, descubre cómo ahorrar y elige la cobertura adecuada para ti.',
    de: 'Versicherungsratgeber: Kfz, Leben, Gesundheit, Haus und Reise. Vergleichen Sie Policen, sparen Sie und wählen Sie den richtigen Schutz für Sie.',
    fr: 'Guide des assurances : auto, vie, santé, habitation et voyage. Comparez les contrats, découvrez comment économiser et choisissez la couverture adaptée.',
    pt: 'Guia de seguros: automóvel, vida, saúde, residência e viagens. Compare apólices, descubra como economizar e escolha a cobertura certa para você.',
  },
  fisco: {
    it: 'Notizie su tasse, dichiarazioni dei redditi, detrazioni e agevolazioni fiscali. Guide pratiche per navigare il fisco italiano e pagare il giusto.',
    en: 'News on taxes, income declarations, deductions and tax breaks. Practical guides to navigate the tax system and pay the right amount.',
    es: 'Noticias sobre impuestos, declaraciones de renta, deducciones y beneficios fiscales. Guías prácticas para navegar el sistema fiscal y pagar lo justo.',
    de: 'Nachrichten zu Steuern, Steuererklärungen, Abzügen und Steuererleichterungen. Praktische Leitfäden zur Navigation im Steuersystem.',
    fr: 'Actualités sur les impôts, déclarations de revenus, déductions et avantages fiscaux. Guides pratiques pour naviguer dans le système fiscal.',
    pt: 'Notícias sobre impostos, declarações de renda, deduções e benefícios fiscais. Guias práticos para navegar no sistema tributário e pagar o valor correto.',
  },
  pensioni: {
    it: 'Tutto sulla previdenza: pensione di vecchiaia, anticipata, invalidità e fondi pensione. Ultime notizie sulle riforme e guide per pianificare il tuo futuro.',
    en: 'Everything about pensions: old age, early retirement, disability and pension funds. Latest news on reforms and guides to plan your future.',
    es: 'Todo sobre pensiones: jubilación, pensión anticipada, invalidez y fondos de pensiones. Últimas noticias sobre reformas y guías para planificar tu futuro.',
    de: 'Alles über Renten: Altersrente, Frühverrentung, Erwerbsminderung und Pensionsfonds. Aktuelle Nachrichten zu Reformen und Leitfäden für Ihre Zukunftsplanung.',
    fr: 'Tout sur les retraites : vieillesse, retraite anticipée, invalidité et fonds de pension. Dernières actualités sur les réformes et guides pour planifier votre avenir.',
    pt: 'Tudo sobre previdência: aposentadoria por idade, antecipada, invalidez e fundos de pensão. Últimas notícias sobre reformas e guias para planejar seu futuro.',
  },
  prestiti: {
    it: 'Guide su prestiti personali, cessione del quinto, carte di credito e finanziamenti. Confronta i migliori tassi e scegli il credito più conveniente per te.',
    en: 'Guides on personal loans, credit assignments, credit cards and financing. Compare the best rates and choose the most convenient credit for you.',
    es: 'Guías sobre préstamos personales, cesión de crédito, tarjetas de crédito y financiación. Compara las mejores tasas y elige el crédito más conveniente para ti.',
    de: 'Leitfäden zu Privatkrediten, Kreditabtretungen, Kreditkarten und Finanzierungen. Vergleichen Sie die besten Zinssätze und wählen Sie den günstigsten Kredit.',
    fr: 'Guides sur les prêts personnels, cessions de crédit, cartes de crédit et financements. Comparez les meilleurs taux et choisissez le crédit le plus avantageux.',
    pt: 'Guias sobre empréstimos pessoais, cessão de crédito, cartões de crédito e financiamentos. Compare as melhores taxas e escolha o crédito mais conveniente para você.',
  },
  trading: {
    it: 'Strategie di trading, analisi dei mercati finanziari, azioni, forex e materie prime. Aggiornamenti in tempo reale per trader principianti ed esperti.',
    en: 'Trading strategies, financial market analysis, stocks, forex and commodities. Real-time updates for beginner and expert traders.',
    es: 'Estrategias de trading, análisis de mercados financieros, acciones, forex y materias primas. Actualizaciones en tiempo real para traders principiantes y expertos.',
    de: 'Handelsstrategien, Finanzmarktanalysen, Aktien, Forex und Rohstoffe. Echtzeit-Updates für Anfänger und erfahrene Trader.',
    fr: 'Stratégies de trading, analyses des marchés financiers, actions, forex et matières premières. Mises à jour en temps réel pour traders débutants et expérimentés.',
    pt: 'Estratégias de trading, análise de mercados financeiros, ações, forex e commodities. Atualizações em tempo real para traders iniciantes e experientes.',
  },
  cucina: {
    it: 'Ricette, tecniche di cottura, prodotti tipici e tendenze food. Dal pranzo veloce alla cena gourmet, trova ispirazione per ogni occasione.',
    en: 'Recipes, cooking techniques, typical products and food trends. From quick lunch to gourmet dinner, find inspiration for every occasion.',
    es: 'Recetas, técnicas de cocina, productos típicos y tendencias gastronómicas. Desde el almuerzo rápido hasta la cena gourmet, encuentra inspiración para cada ocasión.',
    de: 'Rezepte, Kochtechniken, typische Produkte und Food-Trends. Vom schnellen Mittagessen bis zum Gourmet-Dinner — Inspiration für jeden Anlass.',
    fr: "Recettes, techniques de cuisine, produits typiques et tendances food. Du déjeuner rapide au dîner gastronomique, trouvez l'inspiration pour chaque occasion.",
    pt: 'Receitas, técnicas de culinária, produtos típicos e tendências gastronômicas. Do almoço rápido ao jantar gourmet, encontre inspiração para cada ocasião.',
  },
  moda: {
    it: 'Ultime tendenze moda, outfit, sfilate, brand e consigli di stile. Rimani aggiornato sulle collezioni stagionali e i look più trendy del momento.',
    en: 'Latest fashion trends, outfits, runways, brands and style tips. Stay updated on seasonal collections and the trendiest looks of the moment.',
    es: 'Últimas tendencias de moda, outfits, desfiles, marcas y consejos de estilo. Mantente actualizado sobre las colecciones de temporada y los looks más trendy.',
    de: 'Neueste Modetrends, Outfits, Laufstege, Marken und Stiletipps. Bleiben Sie über Saisonkollektionen und die angesagtesten Looks auf dem Laufenden.',
    fr: 'Dernières tendances mode, tenues, défilés, marques et conseils de style. Restez informé des collections saisonnières et des looks les plus tendance du moment.',
    pt: 'Últimas tendências de moda, looks, desfiles, marcas e dicas de estilo. Fique atualizado sobre coleções sazonais e os looks mais trendy do momento.',
  },
  bellezza: {
    it: 'Skincare, makeup, capelli e benessere: tutti i consigli per prenderti cura di te. Review di prodotti, tutorial e tendenze beauty aggiornate.',
    en: 'Skincare, makeup, hair and wellness: all the tips to take care of yourself. Product reviews, tutorials and updated beauty trends.',
    es: 'Skincare, maquillaje, cabello y bienestar: todos los consejos para cuidarte. Reseñas de productos, tutoriales y tendencias beauty actualizadas.',
    de: 'Hautpflege, Make-up, Haare und Wellness: alle Tipps für Ihre Schönheitspflege. Produktrezensionen, Tutorials und aktuelle Beauty-Trends.',
    fr: 'Soins de la peau, maquillage, cheveux et bien-être : tous les conseils pour prendre soin de vous. Critiques de produits, tutoriels et tendances beauté mises à jour.',
    pt: 'Skincare, maquiagem, cabelos e bem-estar: todas as dicas para cuidar de você. Análises de produtos, tutoriais e tendências de beleza atualizadas.',
  },
  animali: {
    it: "Consigli per cani, gatti e altri animali domestici: alimentazione, salute, addestramento e prodotti. Tutto l'amore per i tuoi compagni a quattro zampe.",
    en: 'Tips for dogs, cats and other pets: food, health, training and products. All the love for your four-legged companions.',
    es: 'Consejos para perros, gatos y otras mascotas: alimentación, salud, adiestramiento y productos. Todo el amor para tus compañeros de cuatro patas.',
    de: 'Tipps für Hunde, Katzen und andere Haustiere: Futter, Gesundheit, Training und Produkte. Alle Liebe für Ihre vierbeinigen Gefährten.',
    fr: "Conseils pour chiens, chats et autres animaux de compagnie : alimentation, santé, dressage et produits. Tout l'amour pour vos compagnons à quatre pattes.",
    pt: 'Dicas para cães, gatos e outros animais de estimação: alimentação, saúde, adestramento e produtos. Todo o amor para seus companheiros de quatro patas.',
  },
  ambiente: {
    it: 'Cambiamento climatico, energie rinnovabili, riciclaggio e stile di vita sostenibile. Notizie e guide per vivere in modo più green e rispettoso del pianeta.',
    en: 'Climate change, renewable energy, recycling and sustainable lifestyle. News and guides to live more green and respectful of the planet.',
    es: 'Cambio climático, energías renovables, reciclaje y estilo de vida sostenible. Noticias y guías para vivir de manera más ecológica y respetuosa con el planeta.',
    de: 'Klimawandel, erneuerbare Energien, Recycling und nachhaltiger Lebensstil. Nachrichten und Leitfäden für ein grüneres und umweltfreundlicheres Leben.',
    fr: 'Changement climatique, énergies renouvelables, recyclage et mode de vie durable. Actualités et guides pour vivre de manière plus verte et respectueuse de la planète.',
    pt: 'Mudança climática, energias renováveis, reciclagem e estilo de vida sustentável. Notícias e guias para viver de forma mais verde e respeitosa com o planeta.',
  },
  startup: {
    it: "Notizie su startup, venture capital, imprenditoria e innovazione. Storie di successo, round di finanziamento e consigli per chi vuole avviare un'impresa.",
    en: 'News on startups, venture capital, entrepreneurship and innovation. Success stories, funding rounds and tips for those who want to start a business.',
    es: 'Noticias sobre startups, capital de riesgo, emprendimiento e innovación. Historias de éxito, rondas de financiación y consejos para quienes quieren crear una empresa.',
    de: 'Nachrichten über Startups, Risikokapital, Unternehmertum und Innovation. Erfolgsgeschichten, Finanzierungsrunden und Tipps für Gründer.',
    fr: "Actualités sur les startups, le capital-risque, l'entrepreneuriat et l'innovation. Histoires de succès, levées de fonds et conseils pour créer une entreprise.",
    pt: 'Notícias sobre startups, capital de risco, empreendedorismo e inovação. Histórias de sucesso, rodadas de financiamento e dicas para quem quer abrir um negócio.',
  },
  smartphone: {
    it: 'Recensioni, novità e comparativi di smartphone, tablet e app. Tutto ciò che devi sapere su Android, iOS e le ultime uscite tech.',
    en: 'Reviews, news and comparisons of smartphones, tablets and apps. Everything you need to know about Android, iOS and the latest tech releases.',
    es: 'Reseñas, novedades y comparativas de smartphones, tablets y apps. Todo lo que necesitas saber sobre Android, iOS y los últimos lanzamientos tecnológicos.',
    de: 'Bewertungen, Neuheiten und Vergleiche von Smartphones, Tablets und Apps. Alles über Android, iOS und die neuesten Tech-Releases.',
    fr: 'Avis, nouveautés et comparatifs de smartphones, tablettes et applications. Tout ce que vous devez savoir sur Android, iOS et les dernières sorties tech.',
    pt: 'Análises, novidades e comparativos de smartphones, tablets e apps. Tudo o que você precisa saber sobre Android, iOS e os últimos lançamentos tech.',
  },
  scienza: {
    it: "Scoperte scientifiche, missioni spaziali, fisica, biologia e tecnologia. Aggiornamenti quotidiani dal mondo della ricerca e dell'esplorazione spaziale.",
    en: 'Scientific discoveries, space missions, physics, biology and technology. Daily updates from the world of research and space exploration.',
    es: 'Descubrimientos científicos, misiones espaciales, física, biología y tecnología. Actualizaciones diarias del mundo de la investigación y la exploración espacial.',
    de: 'Wissenschaftliche Entdeckungen, Weltraummissionen, Physik, Biologie und Technologie. Tägliche Updates aus der Welt der Forschung und Weltraumexploration.',
    fr: "Découvertes scientifiques, missions spatiales, physique, biologie et technologie. Mises à jour quotidiennes du monde de la recherche et de l'exploration spatiale.",
    pt: 'Descobertas científicas, missões espaciais, física, biologia e tecnologia. Atualizações diárias do mundo da pesquisa e exploração espacial.',
  },
  psicologia: {
    it: 'Articoli su psicologia, benessere mentale, relazioni e crescita personale. Consigli pratici e approfondimenti scientifici per capire meglio te stesso e gli altri.',
    en: 'Articles on psychology, mental wellness, relationships and personal growth. Practical tips and scientific insights to better understand yourself and others.',
    es: 'Artículos sobre psicología, bienestar mental, relaciones y crecimiento personal. Consejos prácticos e ideas científicas para entenderte mejor a ti mismo y a los demás.',
    de: 'Artikel über Psychologie, psychisches Wohlbefinden, Beziehungen und persönliches Wachstum. Praktische Tipps und wissenschaftliche Erkenntnisse für ein besseres Selbstverständnis.',
    fr: 'Articles sur la psychologie, le bien-être mental, les relations et la croissance personnelle. Conseils pratiques et insights scientifiques pour mieux vous comprendre.',
    pt: 'Artigos sobre psicologia, bem-estar mental, relacionamentos e crescimento pessoal. Dicas práticas e insights científicos para se entender melhor e entender os outros.',
  },
  cinema: {
    it: 'Recensioni di film e serie TV, trailer, notizie dal mondo del cinema e dello streaming. Scopri cosa guardare su Netflix, Prime, Disney+ e molto altro.',
    en: 'Movie and TV series reviews, trailers, news from the world of cinema and streaming. Discover what to watch on Netflix, Prime, Disney+ and much more.',
    es: 'Reseñas de películas y series de TV, tráilers, noticias del mundo del cine y el streaming. Descubre qué ver en Netflix, Prime, Disney+ y mucho más.',
    de: 'Film- und Serienrezensionen, Trailer, Nachrichten aus der Welt des Kinos und Streamings. Entdecken Sie, was auf Netflix, Prime, Disney+ zu sehen ist.',
    fr: 'Critiques de films et séries TV, bandes-annonces, actualités du monde du cinéma et du streaming. Découvrez quoi regarder sur Netflix, Prime, Disney+ et bien plus encore.',
    pt: 'Análises de filmes e séries de TV, trailers, notícias do mundo do cinema e streaming. Descubra o que assistir na Netflix, Prime, Disney+ e muito mais.',
  },
  energia: {
    it: 'Notizie su luce, gas, energie rinnovabili e bollette. Come risparmiare sulle utenze, cambiare fornitore e capire la transizione energetica.',
    en: 'News on electricity, gas, renewable energy and utility bills. How to save on bills, switch providers and understand the energy transition.',
    es: 'Noticias sobre electricidad, gas, energías renovables y facturas. Cómo ahorrar en suministros, cambiar de proveedor y entender la transición energética.',
    de: 'Nachrichten zu Strom, Gas, erneuerbaren Energien und Rechnungen. So sparen Sie bei Versorgungsleistungen und verstehen die Energiewende.',
    fr: "Actualités sur l'électricité, le gaz, les énergies renouvelables et les factures. Comment économiser sur les factures et comprendre la transition énergétique.",
    pt: 'Notícias sobre eletricidade, gás, energias renováveis e contas de consumo. Como economizar nas contas, trocar de fornecedor e entender a transição energética.',
  },
};

export function getNicchiaMeta(id) {
  return NICCHIE_META.find(n => n.id === id) || { colore: '#111', bg: '#f5f5f5' };
}

export function getNicchiaDesc(id, lang) {
  return (NICCHIE_DESC[id] && NICCHIE_DESC[id][lang]) || '';
}
